const samples = [
  { domain: 'infosys.com', type: 'Indian technology company', title: 'Navigate your next with Infosys', summary: 'Infosys helps enterprises in India and around the world with digital transformation, consulting, and technology services.', topics: ['IT services', 'Consulting', 'Digital'], points: ['Provides technology and consulting services to enterprises.', 'Works across cloud, AI, data, and digital engineering.', 'Publishes perspectives on business and technology change.'], audience: 'Enterprise leaders, technology teams, and business decision-makers', headings: ['Services', 'Industries', 'Insights'], links: 39 },
  { domain: 'india.gov.in', type: 'Indian public information', title: 'National Portal of India', summary: 'India.gov.in brings together government information and citizen services from across the Republic of India.', topics: ['Government', 'Citizen services', 'India'], points: ['Connects citizens with government services and information.', 'Organises content by states, ministries, and service areas.', 'Provides access to national news, documents, and resources.'], audience: 'Indian citizens, residents, and public service users', headings: ['Government', 'Services', 'Know India'], links: 76 },
  { domain: 'swayam.gov.in', type: 'Indian education', title: 'SWAYAM: Learn from the best', summary: 'SWAYAM offers online courses from Indian universities and institutions, supporting accessible learning across subjects and levels.', topics: ['Online learning', 'Universities', 'Skills'], points: ['Offers courses from Indian higher education institutions.', 'Covers school, university, and professional learning.', 'Supports learners with structured online course material.'], audience: 'Students, teachers, professionals, and lifelong learners in India', headings: ['Browse courses', 'National coordinators', 'About SWAYAM'], links: 28 },
  { domain: 'isro.gov.in', type: 'Indian research', title: 'Indian Space Research Organisation', summary: 'ISRO shares India’s space missions, scientific programmes, launch services, and applications that support national development.', topics: ['Space', 'Science', 'India'], points: ['Develops launch vehicles and space missions.', 'Uses satellite applications for communication and Earth observation.', 'Publishes mission updates, technology information, and opportunities.'], audience: 'Researchers, students, educators, and space technology professionals', headings: ['Missions', 'Applications', 'About ISRO'], links: 63 },
  { domain: 'tata.com', type: 'Indian business group', title: 'Tata: Leadership with trust', summary: 'Tata presents the businesses, purpose, and community impact of one of India’s long-standing global business groups.', topics: ['Business', 'Leadership', 'Impact'], points: ['Represents companies operating across multiple industries.', 'Connects business performance with a long-term purpose.', 'Highlights innovation, sustainability, and community initiatives.'], audience: 'Customers, investors, partners, and people interested in Indian business', headings: ['Our businesses', 'Community', 'Innovation'], links: 44 },
  { domain: 'pib.gov.in', type: 'Indian news and information', title: 'Press Information Bureau', summary: 'The Press Information Bureau shares official information, announcements, and updates from the Government of India.', topics: ['Government', 'News', 'Public affairs'], points: ['Publishes official government press releases and updates.', 'Organises information by ministry, region, and language.', 'Provides an accessible source for public announcements.'], audience: 'Citizens, journalists, researchers, and public affairs professionals', headings: ['Press releases', 'Features', 'Fact checks'], links: 52 }
];
const $ = (selector) => document.querySelector(selector);
const ANALYZE_ENDPOINT = window.WEBLENS_ANALYZE_ENDPOINT || '/functions/v1/analyze-website';
const SUPABASE_URL = 'https://pbvfpaerwntskhccyocj.supabase.co';
const SUPABASE_ANON_KEY = window.WEBLENS_SUPABASE_ANON_KEY || '';
const sampleGrid = $('#sample-grid');
const modal = $('#detail-modal');
const detailContent = $('#detail-content');
const usageKey = 'weblens-free-analyses';
let remaining = Number(localStorage.getItem(usageKey) ?? 5);

function updateUsage() { $('#usage-count').textContent = `${remaining} free ${remaining === 1 ? 'analysis' : 'analyses'} available`; }
function renderSamples() {
  sampleGrid.innerHTML = samples.map((sample, index) => `<article class="sample-card reveal" style="animation-delay:${index * 70}ms"><div class="card-top"><span>${sample.domain}</span><span class="demo-badge">Demo analysis</span></div><h3>${sample.title}</h3><p class="summary">${sample.summary}</p><div class="topics">${sample.topics.map(topic => `<span class="topic">${topic}</span>`).join('')}</div><button class="card-button" data-sample="${index}">View full analysis <span aria-hidden="true">→</span></button></article>`).join('');
  sampleGrid.addEventListener('click', event => { const button = event.target.closest('[data-sample]'); if (button) openDetail(samples[Number(button.dataset.sample)]); });
}
function openDetail(sample, live = false) {
  detailContent.innerHTML = `<div class="detail-toolbar"><span class="detail-kicker">${live ? 'Live analysis' : 'Demo analysis'} / ${sample.type}</span><div><button class="export-button" id="pdf-export" type="button">Download PDF</button><button class="export-button" id="word-export" type="button">Download Word</button></div></div><h2 id="detail-title">${sample.title}</h2><p class="detail-url">${sample.url ?? `https://${sample.domain}`}</p><div class="detail-block"><h3>AI summary</h3><p>${sample.summary}</p></div><div class="detail-block"><h3>Key points</h3><ul>${sample.points.map(point => `<li>${point}</li>`).join('')}</ul></div><div class="detail-block"><h3>Key topics</h3><div class="topics">${sample.topics.map(topic => `<span class="topic">${topic}</span>`).join('')}</div></div><div class="detail-block"><h3>Target audience</h3><p>${sample.audience}</p></div><div class="detail-block"><h3>Page structure &amp; links</h3><p>${sample.headings.join(' · ')}<br><strong>${sample.links} useful links extracted</strong></p></div><div class="detail-block"><h3>Ask this webpage</h3><form class="question-form" id="question-form"><div class="input-row"><input id="question-input" placeholder="What is this webpage mainly about?" required><button>Ask <span aria-hidden="true">→</span></button></div><p class="answer" id="answer"></p></form></div>`;
  modal.hidden = false; document.body.style.overflow = 'hidden'; const saveButton = document.createElement('button'); saveButton.className = 'export-button'; saveButton.id = 'save-analysis'; saveButton.type = 'button'; saveButton.textContent = 'Save research'; detailContent.querySelector('.detail-toolbar > div').prepend(saveButton);
  saveButton.addEventListener('click', () => saveResearch(sample));
  $('#pdf-export').addEventListener('click', () => exportPdf(sample));
  $('#word-export').addEventListener('click', () => exportWord(sample));
  $('#question-form').addEventListener('submit', event => { event.preventDefault(); $('#answer').textContent = `Based on this ${live ? 'live' : 'demo'} analysis: ${sample.summary}`; });
}
function analysisText(sample) { return `${sample.title}\n${sample.domain}\n\nAI SUMMARY\n${sample.summary}\n\nKEY POINTS\n${sample.points.map(point => `- ${point}`).join('\n')}\n\nKEY TOPICS\n${sample.topics.join(', ')}\n\nTARGET AUDIENCE\n${sample.audience}\n\nPAGE STRUCTURE\n${sample.headings.join(' | ')}\n\nLINKS EXTRACTED\n${sample.links}`; }
function downloadBlob(content, type, filename) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }
function exportWord(sample) { const html = `<html><head><meta charset="utf-8"></head><body><h1>${sample.title}</h1><p>${sample.domain}</p><h2>AI Summary</h2><p>${sample.summary}</p><h2>Key Points</h2><ul>${sample.points.map(point => `<li>${point}</li>`).join('')}</ul><h2>Key Topics</h2><p>${sample.topics.join(', ')}</p><h2>Target Audience</h2><p>${sample.audience}</p><h2>Page Structure</h2><p>${sample.headings.join(' | ')}</p></body></html>`; downloadBlob(html, 'application/msword', `${sample.domain}-weblens-analysis.doc`); }
function exportPdf(sample) { const printWindow = window.open('', '_blank'); if (!printWindow) return; printWindow.document.write(`<html><head><title>WebLens Analysis - ${sample.title}</title><style>body{font-family:Arial,sans-serif;line-height:1.5;padding:40px;color:#162321}h1{font-size:28px}h2{margin-top:28px;border-top:1px solid #ddd;padding-top:12px}</style></head><body><h1>${sample.title}</h1><p>${sample.domain}</p><h2>AI Summary</h2><p>${sample.summary}</p><h2>Key Points</h2><ul>${sample.points.map(point => `<li>${point}</li>`).join('')}</ul><h2>Key Topics</h2><p>${sample.topics.join(', ')}</p><h2>Target Audience</h2><p>${sample.audience}</p><h2>Page Structure</h2><p>${sample.headings.join(' | ')}</p><script>window.onload=()=>window.print();<\/script></body></html>`); printWindow.document.close(); }
function openAccountModal() { $('#account-modal').hidden = false; document.body.style.overflow = 'hidden'; }
function savedResearch() { return JSON.parse(localStorage.getItem('weblens-saved-research') ?? '[]'); }
function saveResearch(sample) { const saved = savedResearch().filter(item => item.domain !== sample.domain); saved.unshift({ ...sample, savedAt: new Date().toISOString() }); localStorage.setItem('weblens-saved-research', JSON.stringify(saved)); renderLibrary(); const button = $('#save-analysis'); if (button) button.textContent = 'Saved'; }
function renderLibrary(query = '') { const results = savedResearch().filter(item => `${item.domain} ${item.title} ${item.summary}`.toLowerCase().includes(query.toLowerCase())); $('#saved-list').innerHTML = results.length ? results.map((item, index) => `<div class="saved-item"><div><strong>${item.title}</strong><span>${item.domain}</span></div><button type="button" data-delete-saved="${index}">Delete</button></div>`).join('') : '<p class="library-empty">Your saved analyses will appear here.</p>'; }
$('#modal-close').addEventListener('click', () => { modal.hidden = true; document.body.style.overflow = ''; });
modal.addEventListener('click', event => { if (event.target === modal) $('#modal-close').click(); });
$('#analyser-form').addEventListener('submit', async event => {
  event.preventDefault(); const input = $('#url-input'); const error = $('#form-error'); error.textContent = '';
  try { const parsed = new URL(input.value); if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error('Please enter a valid public webpage URL.'); } catch { error.textContent = 'Please enter a valid public webpage URL.'; return; }
  if (remaining < 1) { error.textContent = 'You have used your 5 free analyses. Create an account to continue.'; openAccountModal(); return; }
  const status = $('#analysis-status'); status.hidden = false; let progress = 0; const steps = [...document.querySelectorAll('[data-step]')];
  const timer = setInterval(() => { progress = Math.min(progress + 25, 90); $('#progress-bar').style.width = `${progress}%`; $('#status-percent').textContent = `${progress}%`; steps.forEach((step, index) => step.classList.toggle('active', index <= Math.floor(progress / 25))); }, 500);
  try {
    const response = await fetch(ANALYZE_ENDPOINT, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url: input.value }) });
    if (!response.ok) throw new Error('Live analysis is not connected yet. Try a demo analysis below.');
    const analysis = await response.json(); remaining -= 1; localStorage.setItem(usageKey, remaining); updateUsage(); clearInterval(timer); $('#progress-bar').style.width = '100%'; $('#status-percent').textContent = '100%'; openDetail({ ...analysis, title: analysis.title ?? analysis.page_title, summary: analysis.summary ?? analysis.executive_summary, domain: analysis.domain ?? new URL(input.value).hostname, points: analysis.points ?? analysis.key_points ?? [], topics: analysis.topics ?? analysis.key_topics ?? [], audience: analysis.audience ?? analysis.target_audience ?? 'Not found on the webpage.', headings: analysis.headings ?? [], links: Array.isArray(analysis.links) ? analysis.links.length : 0, type: 'Live webpage' }, true);
  } catch (requestError) { clearInterval(timer); status.hidden = true; error.textContent = requestError.message; }
});
$('#research-button').addEventListener('click', () => { document.querySelector('#research').scrollIntoView({ behavior: 'smooth' }); });
$('#library-search').addEventListener('input', event => renderLibrary(event.target.value));
$('#saved-list').addEventListener('click', event => { const button = event.target.closest('[data-delete-saved]'); if (!button) return; const saved = savedResearch(); saved.splice(Number(button.dataset.deleteSaved), 1); localStorage.setItem('weblens-saved-research', JSON.stringify(saved)); renderLibrary($('#library-search').value); });
$('#account-close').addEventListener('click', () => { $('#account-modal').hidden = true; document.body.style.overflow = ''; });
$('#otp-form').addEventListener('submit', async event => { event.preventDefault(); const error = $('#account-error'); error.textContent = ''; if (!SUPABASE_ANON_KEY) { error.textContent = 'Account sign-up is not configured yet.'; return; } const email = $('#email-input').value.trim(); const response = await fetch(`${SUPABASE_URL}/auth/v1/otp`, { method: 'POST', headers: { apikey: SUPABASE_ANON_KEY, 'Content-Type': 'application/json' }, body: JSON.stringify({ email, create_user: true }) }); if (!response.ok) { error.textContent = 'We could not send the code. Please try again.'; return; } $('#otp-label').hidden = false; $('#otp-input').hidden = false; $('#verify-otp').hidden = false; error.textContent = 'Code sent. Check your email.'; });
$('#verify-otp').addEventListener('click', async () => { const error = $('#account-error'); const response = await fetch(`${SUPABASE_URL}/auth/v1/verify`, { method: 'POST', headers: { apikey: SUPABASE_ANON_KEY, 'Content-Type': 'application/json' }, body: JSON.stringify({ email: $('#email-input').value.trim(), token: $('#otp-input').value.trim(), type: 'email' }) }); if (!response.ok) { error.textContent = 'That code is not valid or has expired.'; return; } error.textContent = 'Email verified. Secure checkout will be available when billing is configured.'; $('#payment-button').disabled = false; });
$('#payment-button').addEventListener('click', () => { alert('Payments require a dedicated provider such as Stripe. An OpenAI API key is used for AI analysis, not payment processing.'); });
updateUsage(); renderSamples(); renderLibrary();
