const samples = [
  { domain: 'stripe.com', type: 'Technology', title: 'Financial infrastructure for the internet', summary: 'Stripe gives businesses the tools to accept payments, send payouts, and manage financial operations online.', topics: ['Payments', 'Business', 'Infrastructure'], points: ['Supports online and in-person payment experiences.', 'Offers tools for billing, tax, fraud prevention, and reporting.', 'Designed for startups through large global enterprises.'], audience: 'Internet businesses, startups, and enterprise teams', headings: ['Financial infrastructure', 'Products and services', 'Global growth'], links: 26 },
  { domain: 'who.int', type: 'Public information', title: 'World Health Organization', summary: 'The WHO directs and coordinates international health within the United Nations system and shares evidence-led health guidance.', topics: ['Health', 'Policy', 'Global impact'], points: ['Publishes health information and scientific guidance.', 'Coordinates responses to health emergencies.', 'Works with countries to improve population health.'], audience: 'Public health professionals, governments, and the general public', headings: ['Health topics', 'Countries', 'Emergencies'], links: 84 },
  { domain: 'ocw.mit.edu', type: 'Education', title: 'MIT OpenCourseWare', summary: 'MIT OpenCourseWare makes the materials from thousands of MIT courses available freely online for learners around the world.', topics: ['Learning', 'Research', 'Open access'], points: ['Provides lecture notes, exams, and videos from MIT courses.', 'Covers a wide range of academic disciplines.', 'Content is available without registration or payment.'], audience: 'Independent learners, educators, and students', headings: ['Find courses', 'Topics', 'About OCW'], links: 41 },
  { domain: 'nasa.gov', type: 'Research', title: 'NASA: Explore the universe', summary: 'NASA shares missions, discoveries, and research that expand human knowledge of Earth, the solar system, and the universe.', topics: ['Space', 'Science', 'Discovery'], points: ['Reports on current missions and scientific discoveries.', 'Offers educational resources and imagery.', 'Connects space exploration with life on Earth.'], audience: 'Researchers, students, educators, and space enthusiasts', headings: ['Missions', 'Science', 'The solar system'], links: 67 },
  { domain: 'patagonia.com', type: 'Company', title: 'We are in business to save our home planet', summary: 'Patagonia presents its outdoor products alongside a strong commitment to environmental responsibility and activism.', topics: ['Climate', 'Retail', 'Activism'], points: ['Sells outdoor clothing and equipment.', 'Emphasises repair, reuse, and responsible materials.', 'Uses its business to support environmental action.'], audience: 'Outdoor consumers and environmentally conscious communities', headings: ['Shop', 'Activism', 'Our footprint'], links: 32 },
  { domain: 'unicef.org', type: 'NGO', title: 'For every child', summary: 'UNICEF works in more than 190 countries and territories to protect children’s rights and help them reach their potential.', topics: ['Children', 'Development', 'Human rights'], points: ['Responds to emergencies affecting children.', 'Supports health, education, and protection programmes.', 'Works with partners in countries and communities.'], audience: 'Donors, advocates, policymakers, and families', headings: ['What we do', 'Where we work', 'Take action'], links: 58 }
];
const $ = (selector) => document.querySelector(selector);
const ANALYZE_ENDPOINT = window.WEBLENS_ANALYZE_ENDPOINT || '/functions/v1/analyze-website';
const sampleGrid = $('#sample-grid');
const modal = $('#detail-modal');
const detailContent = $('#detail-content');
const usageKey = 'weblens-free-analyses';
let remaining = Number(localStorage.getItem(usageKey) ?? 5);

function updateUsage() { $('#usage-count').textContent = `${remaining} free ${remaining === 1 ? 'analysis' : 'analyses'} available`; }
function renderSamples() {
  sampleGrid.innerHTML = samples.map((sample, index) => `<article class="sample-card reveal" style="animation-delay:${index * 70}ms"><div class="card-top"><span>${sample.domain}</span><span class="demo-badge">Demo analysis</span></div><h3>${sample.title}</h3><p class="summary">${sample.summary}</p><div class="topics">${sample.topics.map(topic => `<span class="topic">${topic}</span>`).join('')}</div><button class="card-button" data-sample="${index}">View full analysis <span aria-hidden="true">→</span></button></article>`).join('');
  sampleGrid.addEventListener('click', event => { const button = event.target.closest('[data-sample]'); if (button) openDetail(samples[Number(button.dataset.sample)]); });
}
function openDetail(sample, live = false) {
  detailContent.innerHTML = `<span class="detail-kicker">${live ? 'Live analysis' : 'Demo analysis'} / ${sample.type}</span><h2 id="detail-title">${sample.title}</h2><p class="detail-url">${sample.domain}</p><div class="detail-block"><h3>AI summary</h3><p>${sample.summary}</p></div><div class="detail-block"><h3>Key points</h3><ul>${sample.points.map(point => `<li>${point}</li>`).join('')}</ul></div><div class="detail-block"><h3>Key topics</h3><div class="topics">${sample.topics.map(topic => `<span class="topic">${topic}</span>`).join('')}</div></div><div class="detail-block"><h3>Target audience</h3><p>${sample.audience}</p></div><div class="detail-block"><h3>Page structure &amp; links</h3><p>${sample.headings.join(' · ')}<br><strong>${sample.links} useful links extracted</strong></p></div><div class="detail-block"><h3>Ask this webpage</h3><form class="question-form" id="question-form"><div class="input-row"><input id="question-input" placeholder="What is this webpage mainly about?" required><button>Ask <span aria-hidden="true">→</span></button></div><p class="answer" id="answer"></p></form></div>`;
  modal.hidden = false; document.body.style.overflow = 'hidden';
  $('#question-form').addEventListener('submit', event => { event.preventDefault(); $('#answer').textContent = `Based on this ${live ? 'live' : 'demo'} analysis: ${sample.summary}`; });
}
$('#modal-close').addEventListener('click', () => { modal.hidden = true; document.body.style.overflow = ''; });
modal.addEventListener('click', event => { if (event.target === modal) $('#modal-close').click(); });
$('#analyser-form').addEventListener('submit', async event => {
  event.preventDefault(); const input = $('#url-input'); const error = $('#form-error'); error.textContent = '';
  try { const parsed = new URL(input.value); if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error('Please enter a valid public webpage URL.'); } catch { error.textContent = 'Please enter a valid public webpage URL.'; return; }
  if (remaining < 1) { error.textContent = 'You have used your 5 free analyses. Create an account to continue.'; return; }
  const status = $('#analysis-status'); status.hidden = false; let progress = 0; const steps = [...document.querySelectorAll('[data-step]')];
  const timer = setInterval(() => { progress = Math.min(progress + 25, 90); $('#progress-bar').style.width = `${progress}%`; $('#status-percent').textContent = `${progress}%`; steps.forEach((step, index) => step.classList.toggle('active', index <= Math.floor(progress / 25))); }, 500);
  try {
    const response = await fetch(ANALYZE_ENDPOINT, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url: input.value }) });
    if (!response.ok) throw new Error('Live analysis is not connected yet. Try a demo analysis below.');
    const analysis = await response.json(); remaining -= 1; localStorage.setItem(usageKey, remaining); updateUsage(); clearInterval(timer); $('#progress-bar').style.width = '100%'; $('#status-percent').textContent = '100%'; openDetail({ ...analysis, title: analysis.title ?? analysis.page_title, summary: analysis.summary ?? analysis.executive_summary, domain: analysis.domain ?? new URL(input.value).hostname, points: analysis.points ?? analysis.key_points ?? [], topics: analysis.topics ?? analysis.key_topics ?? [], audience: analysis.audience ?? analysis.target_audience ?? 'Not found on the webpage.', headings: analysis.headings ?? [], links: Array.isArray(analysis.links) ? analysis.links.length : 0, type: 'Live webpage' }, true);
  } catch (requestError) { clearInterval(timer); status.hidden = true; error.textContent = requestError.message; }
});
$('#research-button').addEventListener('click', () => { alert('Saved research is ready for the next build step.'); });
updateUsage(); renderSamples();
